### PR TITLE
Expose progress bar link click event. Move href check within this fun…

### PR DESCRIPTION
**Pull request by gamma613**
1. Expose the progress bar link click event, folks can write their own custom Link component and handle the event themselves if desired

2. instead of checking existence / properties of href attribute upon component instantiation, check it using this function in realtime.

### CODE REVIEW

**Comment by designly1** [comment]
> 1. Expose the progress bar link click event, folks can write their own custom Link component and handle the event themselves if desired
> 
>     2. instead of checking existence / properties of href attribute upon component instantiation, check it using this function in realtime.

Could you update the README too with a short explanation? Thanks for your contribution!

**Comment by designly1** [comment]
Also, feel free to add yourself as a contributor to the package.json :-)

**Comment by gamma613** [comment]
Good call! Added, with some basic examples. Hopefully it's clear

**Comment by designly1** [comment]
Merged and closed. Thank you! ;_)

**Comment by gamma613** [comment]
I took a look at the latest on `npm` but the changes don't seem to be appearing. I am wondering if the new package may have skipped the build process or used a cached build?

**Comment by designly1** [comment]
I see that. I deleting everything and rebuilt. Tsup is kind of weird 
sometimes. Or it's very possible I just forgot to run it. :D Published 
as 1.2.1.

Jay


------ Original Message ------
From "Steven McCoy" ***@***.***>
To "designly1/nextjs13-progress" ***@***.***>
Cc "Jay Simons" ***@***.***>; "State change" 
***@***.***>
Date 1/2/2024 9:04:34 AM
Subject Re: [designly1/nextjs13-progress] Expose progress bar link click 
event. Move href check within this fun… (PR #2)

**Pull request merged**
